# Generated by Django 4.0 on 2022-01-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('about_info', models.TextField()),
                ('home_info', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
        ),
    ]
