# Generated by Django 4.0 on 2022-01-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_owner_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='gender',
            field=models.CharField(max_length=100),
        ),
    ]
