# Generated by Django 4.0 on 2022-01-30 10:52

from django.db import migrations, models
import owner.models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_alter_owner_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='photo',
            field=models.ImageField(blank=True, default='default-profile.png', upload_to='', validators=[owner.models.file_size]),
        ),
    ]
