# Generated by Django 4.0 on 2022-02-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of contact info', max_length=100)),
                ('details', models.CharField(help_text='Contact info', max_length=200)),
                ('type', models.CharField(choices=[('PH', 'Phone Number'), ('LI', 'Link'), ('EM', 'Email Address'), ('TE', 'Other Text')], help_text='What kind of contact information is this?', max_length=2)),
            ],
        ),
    ]
