# Generated by Django 4.0 on 2022-02-02 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='details',
            new_name='info',
        ),
    ]
