# Generated by Django 4.0 on 2022-02-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_details_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='order_no',
            field=models.IntegerField(default=1, max_length=2),
        ),
    ]
