# Generated by Django 4.0 on 2022-02-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='order_no',
            field=models.IntegerField(max_length=2),
        ),
    ]
