# Generated by Django 4.0 on 2022-01-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
