# Generated by Django 4.0 on 2022-01-30 10:52

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='default-thumbnail.jpg', upload_to='', validators=[projects.models.file_size]),
        ),
    ]
