# Generated by Django 4.0 on 2022-01-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
