# Generated by Django 4.0 on 2022-01-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('education', models.CharField(help_text='The title of degree or education', max_length=100)),
                ('stating_year', models.PositiveSmallIntegerField()),
                ('ending_year', models.PositiveSmallIntegerField()),
                ('info', models.TextField()),
            ],
        ),
    ]
