# Generated by Django 4.0 on 2022-01-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='ending_year',
            field=models.PositiveSmallIntegerField(default=' '),
        ),
    ]
