# Generated by Django 4.0 on 2022-01-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_alter_education_ending_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='school_name',
            field=models.CharField(max_length=101),
        ),
    ]
