# Generated by Django 4.0 on 2022-01-30 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_rename_stating_year_education_starting_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='education',
            new_name='title',
        ),
    ]
