# Generated by Django 4.0 on 2022-01-28 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_set_number', models.CharField(help_text='The number a skill set the skill is organized under', max_length=150)),
                ('limited_integer_field', models.IntegerField(default=1, help_text='How good are you in this skill in procents', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(help_text='The title of the skill set', max_length=100)),
            ],
        ),
    ]
