# Generated by Django 4.0 on 2022-01-28 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_set_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skillset'),
        ),
    ]
