# Generated by Django 4.0 on 2022-01-28 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skill_skill_set_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='limited_integer_field',
            new_name='skill_in_procents',
        ),
    ]
