# Generated by Django 4.0 on 2022-01-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_rename_limited_integer_field_skill_skill_in_procents'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_title',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
