# Generated by Django 4.0 on 2022-01-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_skill_skill_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_title',
            field=models.CharField(max_length=100),
        ),
    ]
