# Generated by Django 4.0 on 2022-01-29 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_alter_skill_skill_in_procents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill_set_number',
            new_name='skill_set',
        ),
    ]
