# Generated by Django 4.0 on 2022-01-29 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0008_rename_skill_in_procents_skill_skill_procents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill_procents',
            new_name='procents',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skill_title',
            new_name='title',
        ),
    ]
