# Generated by Django 4.0 on 2022-01-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0010_remove_skillset_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillset',
            name='order_number',
            field=models.PositiveSmallIntegerField(default=0, help_text='The order the skill set should be on the page'),
        ),
    ]
