# Generated by Django 4.0 on 2022-01-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0011_skillset_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillset',
            name='order_number',
            field=models.PositiveSmallIntegerField(help_text='The order the skill set should be on the page'),
        ),
    ]
