# Generated by Django 4.0 on 2022-02-25 00:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0012_alter_skillset_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='procents',
            field=models.IntegerField(default=1, help_text='How good are you in this skill in procents (0-100%)', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
