# Generated by Django 4.0 on 2022-02-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0013_alter_skill_procents'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillset',
            name='image',
            field=models.ImageField(default='bullet.png', upload_to=''),
        ),
    ]
