# Generated by Django 4.0 on 2022-02-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0014_skillset_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillset',
            name='image',
        ),
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(default='bullet.png', upload_to=''),
        ),
    ]
